List<String> maincateg = [
  'Select State',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Orissa',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal'
];

List<String> AndhraPradesh = [
  'District',
  'Alluri Sitharama Raju',
  'Anakapalli',
  'Anantapur',
  'Annamayya',
  'Bapatla',
  'Chittoor',
  'East Godavari',
  'Eluru',
  'Guntur',
  'Kakinada',
  'Konaseema',
  'Krishna',
  'Kurnool',
  'NTR',
  'Nandyal',
  'Palnadu',
  'Parvathipuram Manyam',
  'Prakasam',
  'SPSR Nellore',
  'Sri Sathya Sai',
  'Srikakulam',
  'Tirupati',
  'Visakhapatanam',
  'Vizianagaram',
  'West Godavari',
  'Y.S.R'
];

List<String> ArunachalPradesh = [
  'District',
  'ANJAW',
  'Changlang',
  'Dibang Valley',
  'East Kameng',
  'East Siang',
  'Kamle',
  'Kra Daadi',
  'Kurung Kumey',
  'Leparada',
  'Lohit',
  'Longding',
  'Lower Dibang Valley',
  'Lower Siang',
  'Lower Subansiri',
  'Namsai',
  'Pakke Kessang',
  'Papum Pare',
  'SHI YOMI',
  'Siang',
  'Tawang',
  'Tirap',
  'Upper Siang',
  'Upper Subansiri',
  'West Kameng',
  'West Siang',
];

List<String> Assam = [
  'District',
  'Baksa',
  'Barpeta',
  'Bongaigaon',
  'Cachar',
  'Charaideo',
  'Chirang',
  'Darrang',
  'Dhemaji',
  'Dhubri',
  'Dibrugarh',
  'Dima Hasao',
  'Goalpara',
  'Golaghat',
  'Hailakandi',
  'Jorhat',
  'Kamrup Metropolitan',
  'Kamrup',
  'Karbi Anglong',
  'Karimganj',
  'Kokrajhar',
  'Lakhimpur',
  'Majuli',
  'Morigaon',
  'Nagaon',
  'Nalbari',
  'Sivasagar',
  'Sonitpur',
  'South Salmara-Mankachar',
  'Tinsukia',
  'Udalguri',
  'West Karbi Anglong',
];

List<String> Bihar = [
  'District',
  'Araria',
  'Arwal',
  'Aurangabad',
  'Banka',
  'Begusarai',
  'Bhagalpur',
  'Bhojpur',
  'Buxar',
  'Darbhanga',
  'Gaya',
  'Gopalganj',
  'Jamui',
  'Jehanabad',
  'Kaimur',
  'Katihar',
  'Khagaria',
  'Kishanganj',
  'Lakhisarai',
  'Madhepura',
  'Madhubani',
  'Munger',
  'Muzaffarpur',
  'Nalanda',
  'Nawada',
  'Pashchim Champaran',
  'Patna',
  'Purba Champaran',
  'Purnia',
  'Rohtas',
  'Saharsa',
  'Samastipur',
  'Saran',
  'Sheikhpura',
  'Sheohar',
  'Sitamarhi',
  'Siwan',
  'Supaul',
  'Vaishali',
];

List<String> Chhattisgarh = [
  'District',
  'Balod',
  'Baloda Bazar',
  'Balrampur',
  'Bastar',
  'Bemetara',
  'Bijapur',
  'Bilaspur',
  'Dantewada',
  'Dhamtari',
  'Durg',
  'Gariaband',
  'Janjgir-Champa',
  'Jashpur',
  'Kabirdham',
  'Kanker',
  'Kondagaon',
  'Korba',
  'Koriya',
  'Mahasamund',
  'Mungeli',
  'Narayanpur',
  'Raigarh',
  'Raipur',
  'Rajnandgaon',
  'Sukma',
  'Surajpur',
  'Surguja',
];

List<String> Goa = [
  'District',
  'North Goa',
  'South Goa',
];

List<String> Gujarat = [
  'District',
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Aravalli',
  'Banaskantha',
  'Bharuch',
  'Bhavnagar',
  'Botad',
  'Chhota Udaipur',
  'Dahod',
  'Dang',
  'Devbhoomi Dwarka',
  'Gandhinagar',
  'Gir Somnath',
  'Jamnagar',
  'Junagadh',
  'Kutch',
  'Kheda',
  'Mahisagar',
  'Mehsana',
  'Morbi',
  'Narmada',
  'Navsari',
  'Panchmahal',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar',
  'Tapi',
  'Vadodara',
  'Valsad',
];

List<String> Haryana = [
  'District',
  'Ambala',
  'Bhiwani',
  'Charkhi Dadri',
  'Faridabad',
  'Fatehabad',
  'Gurugram',
  'Hisar',
  'Jhajjar',
  'Jind',
  'Kaithal',
  'Karnal',
  'Kurukshetra',
  'Mahendragarh',
  'Nuh',
  'Palwal',
  'Panchkula',
  'Panipat',
  'Rewari',
  'Rohtak',
  'Sirsa',
  'Sonipat',
  'Yamunanagar',
];

List<String> HimachalPradesh = [
  'District',
  'Bilaspur',
  'Chamba',
  'Hamirpur',
  'Kangra',
  'Kinnaur',
  'Kullu',
  'Lahaul and Spiti',
  'Mandi',
  'Shimla',
  'Sirmaur',
  'Solan',
  'Una',
];
List<String> Jharkhand = [
  'District',
  'Bokaro',
  'Chatra',
  'Deoghar',
  'Dhanbad',
  'Dumka',
  'East Singhbhum',
  'Garhwa',
  'Giridih',
  'Godda',
  'Gumla',
  'Hazaribagh',
  'Jamtara',
  'Khunti',
  'Koderma',
  'Latehar',
  'Lohardaga',
  'Pakur',
  'Palamu',
  'Ramgarh',
  'Ranchi',
  'Sahebganj',
  'Seraikela',
  'Simdega',
  'West Singhbhum',
];
List<String> Karnataka = [
  'District',
  'Bagalkot',
  'Bengaluru Urban',
  'Bengaluru Rural',
  'Belagavi',
  'Ballari',
  'Bidar',
  'Vijayapur',
  'Chamarajanagar',
  'Chikballapur',
  'Chikkamagaluru',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Kalaburagi',
  'Hassan',
  'Haveri',
  'Kodagu',
  'Kolar',
  'Koppal',
  'Mandya',
  'Mysuru',
  'Raichur',
  'Ramanagara',
  'Shivamogga',
  'Tumakuru',
  'Udupi',
  'Uttara Kannada',
  'Yadgir',
];
List<String> Kerala = [
  'District',
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasaragod',
  'Kollam',
  'Kottayam',
  'Kozhikode',
  'Malappuram',
  'Palakkad',
  'Pathanamthitta',
  'Thiruvananthapuram',
  'Thrissur',
  'Wayanad',
];
List<String> MadhyaPradesh = [
  'District',
  'Agar Malwa',
  'Alirajpur',
  'Anuppur',
  'Ashoknagar',
  'Balaghat',
  'Barwan',
  'Betul',
  'Bhind',
  'Bhopal',
  'Burhanpur',
  'Chhatarpur',
  'Chhindwara',
  'Damoh',
  'Datia',
  'Dewas',
  'Dhar',
  'Dindori',
  'East Nimar',
  'Guna',
  'Gwalior',
  'Harda',
  'Hoshangabad',
  'Indore',
  'Jabalpur',
  'Jhabua',
  'Katni',
  'Mandla',
  'Mandsaur',
  'Morena',
  'Narsinghpur',
  'Neemuch',
  'Niwari',
  'Panna',
  'Raisen',
  'Rajgarh',
  'Ratlam',
  'Rewa',
  'Sagar',
  'Satna',
  'Sehore',
  'Seoni',
  'Shahdol',
  'Shajapur',
  'Sheopur',
  'Shivpuri',
  'Sidhi',
  'Singrauli',
  'Tikamgarh',
  'Ujjain',
  'Umaria',
  'Vidisha',
  'West Nimar',
];
List<String> Maharashtra = [
  'District',
  'Ahmednagar',
  'Akola',
  'Amravati',
  'Aurangabad',
  'Beed',
  'Bhandara',
  'Buldhana',
  'Chandrapur',
  'Dhule',
  'Gadchiroli',
  'Gondia',
  'Hingoli',
  'Jalgaon',
  'Jalna',
  'Kolhapur',
  'Latur',
  'Mumbai City',
  'Mumbai Suburban',
  'Nagpur',
  'Nanded',
  'Nandurbar',
  'Nashik',
  'Osmanabad',
  'Palghar',
  'Parbhani',
  'Pune',
  'Raigad',
  'Ratnagiri',
  'Sangli',
  'Satara',
  'Sindhudurg',
  'Solapur',
  'Thane',
  'Wardha',
  'Washim',
  'Yavatmal',
];
List<String> Manipur = [
  'District',
  'Bishnupur',
  'Thoubal',
  'Imphal East',
  'Imphal West',
  'Senapati',
  'Ukhrul',
  'Chandel',
  'Churachandpur',
  'Tamenglong',
];
List<String> Meghalaya = [
  'District',
  'East Garo Hills',
  'East Khasi Hills',
  'Jaintia Hills',
  'Ri Bhoi',
  'South Garo Hills',
  'West Garo Hills',
  'West Khasi Hills',
];
List<String> Mizoram = [
  'District',
  'Aizawl',
  'Kolasib',
  'Lawngtlai',
  'Lunglei',
  'Mamit',
  'Saiha',
  'Serchhip',
  'Champhai',
];
List<String> Nagaland = [
  'District',
  'Dimapur',
  'Kiphire',
  'Kohima',
  'Longleng',
  'Mokokchung',
  'Mon',
  'Peren',
  'Phek',
  'Tuensang',
  'Wokha',
  'Zunheboto',
  'Noklak',
];
List<String> Orissa = [
  'District',
  'Angul',
  'Boudh (Baudh)',
  'Balangir',
  'Bargarh',
  'Balasore (Baleswar)',
  'Bhadrak',
  'Cuttack',
  'Deogarh (Debagarh)',
  'Dhenkanal',
  'Ganjam',
  'Gajapati',
  'Jharsuguda',
  'Jajpur',
  'Jagatsinghapur',
  'Khordha',
  'Keonjhar (Kendujhar)',
  'Kalahandi',
  'Kandhamal',
  'Koraput',
  'Kendrapara',
  'Malkangiri',
  'Mayurbhanj',
  'Nabarangpur',
  'Nuapada',
  'Nayagarh',
  'Puri',
  'Rayagada',
  'Sambalpur',
  'Subarnapur (Sonepur)',
  'Sundargarh',
];
List<String> Punjab = [
  'District',
  'Amritsar',
  'Barnala',
  'Bathinda',
  'Faridkot',
  'Fatehgarh Sahib',
  'Firozpur',
  'Fazilka',
  'Gurdaspur',
  'Hoshiarpur',
  'Jalandhar',
  'Kapurthala',
  'Ludhiana',
  'Mansa',
  'Moga',
  'Sri Muktsar Sahib',
  'Pathankot',
  'Patiala',
  'Rupnagar',
  'Sahibzada Ajit Singh Nagar',
  'Sangrur',
  'Shahid Bhagat Singh Nagar',
  'Taran Taran',
];
List<String> Rajasthan = [
  'District',
  'Ajmer',
  'Alwar',
  'Banswara',
  'Baran',
  'Barmer',
  'Bharatpur',
  'Bhilwara',
  'Bikaner',
  'Bundi',
  'Chittorgarh',
  'Churu',
  'Dausa',
  'Dholpur',
  'Dungarpur',
  'Hanumangarh',
  'Jaipur',
  'Jaisalmer',
  'Jalor',
  'Jhalawar',
  'Jhunjhunu',
  'Jodhpur',
  'Karauli',
  'Kota',
  'Nagaur',
  'Pali',
  'Pratapgarh',
  'Rajsamand',
  'Sawai Madhopur',
  'Sikar',
  'Sirohi',
  'Sri Ganganagar',
  'Tonk',
  'Udaipur',
];
List<String> Sikkim = [
  'District',
  'East Sikkim',
  'North Sikkim',
  'South Sikkim',
  'West Sikkim',
];
List<String> TamilNadu = [
  'District',
  'Ariyalur',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kanchipuram',
  'Kanniyakumari',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Nagapattinam',
  'Namakkal',
  'Nilgiris',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Salem',
  'Sivaganga',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
];
List<String> Telangana = [
  'District',
  'Adilabad',
  'Bhadradri Kothagudem',
  'Hyderabad',
  'Jagitial',
  'Jangaon',
  'Jayashankar Bhupalapally',
  'Jogulamba Gadwal',
  'Kamareddy',
  'Karimnagar',
  'Khammam',
  'Kumarambheem Asifabad',
  'Mahabubabad',
  'Mahabubnagar',
  'Mancherial district',
  'Medak',
  'Medchal–Malkajgiri',
  'Mulugu',
  'Nagarkurnool',
  'Narayanpet',
  'Nalgonda',
  'Nirmal',
  'Nizamabad',
  'Peddapalli',
  'Rajanna Sircilla',
  'Ranga Reddy',
  'Sangareddy',
  'Siddipet',
  'Suryapet',
  'Vikarabad',
  'Wanaparthy',
  'Warangal Rural',
  'Warangal Urban',
  'Yadadri Bhuvanagiri',
];
List<String> Tripura = [
  'District',
  'Dhalai',
  'North Tripura',
  'South Tripura',
  'West Tripura',
];
List<String> UttarPradesh = [
  'District',
  'Agra',
  'Aligarh',
  'PrayagRaj',
  'Ambedkar Nagar',
  'Amroha',
  'Auraiya',
  'Azamgarh',
  'Badaun',
  'Bahraich',
  'Ballia',
  'Balrampur',
  'Banda District',
  'Barabanki',
  'Bareilly',
  'Basti',
  'Bijnor',
  'Bulandshahr',
  'Chandauli(Varanasi Dehat)',
  'Chitrakoot',
  'Deoria',
  'Etah',
  'Etawah',
  'Faizabad',
  'Farrukhabad',
  'Fatehpur',
  'Firozabad',
  'Gautam Buddha Nagar',
  'Ghaziabad',
  'Ghazipur',
  'Gonda',
  'Gorakhpur',
  'Hamirpur',
  'Hapur District',
  'Hardoi',
  'Hathras',
  'Jaunpur District',
  'Jhansi',
  'Kannauj',
  'Kanpur Dehat',
  'Kanpur Nagar',
  'Kasganj',
  'Kaushambi',
  'Kushinagar',
  'Lakhimpur Kheri',
  'Lalitpur',
  'Lucknow',
  'Maharajganj',
  'Mahoba',
  'Mainpuri',
  'Mathura',
  'Mau',
  'Meerut',
  'Mirzapur',
  'Moradabad',
  'Muzaffarnagar',
  'Pilibhit',
  'Pratapgarh',
  'Rae Bareli',
  'Rampur',
  'Saharanpur',
  'Sant Kabir Nagar',
  'Sant Ravidas Nagar',
  'Sambhal',
  'Shahjahanpur',
  'Shamli',
  'Shravasti',
  'Siddharthnagar',
  'Sitapur',
  'Sonbhadra',
  'Sultanpur',
  'Unnao',
  'Varanasi (Kashi)',
  'Allahabad',
  'Amethi',
  'Bagpat',
];
List<String> Uttarakhand = [
  'District',
  'Almora',
  'Bageshwar',
  'Chamoli',
  'Champawat',
  'Dehradun',
  'Haridwar',
  'Nainital',
  'Pauri Garhwal',
  'Pithoragarh',
  'Rudraprayag',
  'Tehri Garhwal',
  'Udham Singh Nagar',
  'Uttarkashi',
];
List<String> WestBengal = [
  'District',
  'Alipurduar',
  'Bankura',
  'Birbhum',
  'Cooch Behar',
  'Dakshin Dinajpur',
  'Darjeeling',
  'Hooghly',
  'Howrah',
  'Jalpaiguri',
  'Jhargram',
  'Kalimpong',
  'Kolkata',
  'Malda',
  'Murshidabad',
  'Nadia',
  'North 24 Parganas',
  'Paschim Bardhaman',
  'Paschim Medinipur',
  'Purba Bardhaman',
  'Purba Medinipur',
  'Purulia',
  'South 24 Parganas',
  'Uttar Dinajpur',
];
